export interface Country {
  name: string;
  code: string;
  unicode: string;
  emoji: string;
  dialCode: string;
}

export const countries: Country[] = [
  {
    name: "Aruba",
    code: "AW",
    unicode: "U+1F1E6 U+1F1FC",
    emoji: "🇦🇼",
    dialCode: "+297",
  },
  {
    name: "Afghanistan",
    code: "AF",
    unicode: "U+1F1E6 U+1F1EB",
    emoji: "🇦🇫",
    dialCode: "+93",
  },
  {
    name: "Angola",
    code: "AO",
    unicode: "U+1F1E6 U+1F1F4",
    emoji: "🇦🇴",
    dialCode: "+244",
  },
  {
    name: "Anguilla",
    code: "AI",
    unicode: "U+1F1E6 U+1F1EE",
    emoji: "🇦🇮",
    dialCode: "+1-264",
  },
  {
    name: "Åland Islands",
    code: "AX",
    unicode: "U+1F1E6 U+1F1FD",
    emoji: "🇦🇽",
    dialCode: "+358 18",
  },
  {
    name: "Albania",
    code: "AL",
    unicode: "U+1F1E6 U+1F1F1",
    emoji: "🇦🇱",
    dialCode: "+355",
  },
  {
    name: "Andorra",
    code: "AD",
    unicode: "U+1F1E6 U+1F1E9",
    emoji: "🇦🇩",
    dialCode: "+376",
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    unicode: "U+1F1E6 U+1F1EA",
    emoji: "🇦🇪",
    dialCode: "+971",
  },
  {
    name: "Argentina",
    code: "AR",
    unicode: "U+1F1E6 U+1F1F7",
    emoji: "🇦🇷",
    dialCode: "+54",
  },
  {
    name: "Armenia",
    code: "AM",
    unicode: "U+1F1E6 U+1F1F2",
    emoji: "🇦🇲",
    dialCode: "+374",
  },
  {
    name: "American Samoa",
    code: "AS",
    unicode: "U+1F1E6 U+1F1F8",
    emoji: "🇦🇸",
    dialCode: "+1-684",
  },
  {
    name: "Antarctica",
    code: "AQ",
    unicode: "U+1F1E6 U+1F1F6",
    emoji: "🇦🇶",
    dialCode: "+672",
  },
  {
    name: "French Southern Territories",
    code: "TF",
    unicode: "U+1F1F9 U+1F1EB",
    emoji: "🇹🇫",
    dialCode: "+262",
  },
  {
    name: "Antigua and Barbuda",
    code: "AG",
    unicode: "U+1F1E6 U+1F1EC",
    emoji: "🇦🇬",
    dialCode: "+1-268",
  },
  {
    name: "Australia",
    code: "AU",
    unicode: "U+1F1E6 U+1F1FA",
    emoji: "🇦🇺",
    dialCode: "+61",
  },
  {
    name: "Austria",
    code: "AT",
    unicode: "U+1F1E6 U+1F1F9",
    emoji: "🇦🇹",
    dialCode: "+43",
  },
  {
    name: "Azerbaijan",
    code: "AZ",
    unicode: "U+1F1E6 U+1F1FF",
    emoji: "🇦🇿",
    dialCode: "+994",
  },
  {
    name: "Burundi",
    code: "BI",
    unicode: "U+1F1E7 U+1F1EE",
    emoji: "🇧🇮",
    dialCode: "+257",
  },
  {
    name: "Belgium",
    code: "BE",
    unicode: "U+1F1E7 U+1F1EA",
    emoji: "🇧🇪",
    dialCode: "+32",
  },
  {
    name: "Benin",
    code: "BJ",
    unicode: "U+1F1E7 U+1F1EF",
    emoji: "🇧🇯",
    dialCode: "+229",
  },
  {
    name: "Bonaire, Sint Eustatius and Saba",
    code: "BQ",
    unicode: "U+1F1E7 U+1F1F6",
    emoji: "🇧🇶",
    dialCode: "+599",
  },
  {
    name: "Burkina Faso",
    code: "BF",
    unicode: "U+1F1E7 U+1F1EB",
    emoji: "🇧🇫",
    dialCode: "+226",
  },
  {
    name: "Bangladesh",
    code: "BD",
    unicode: "U+1F1E7 U+1F1E9",
    emoji: "🇧🇩",
    dialCode: "+880",
  },
  {
    name: "Bulgaria",
    code: "BG",
    unicode: "U+1F1E7 U+1F1EC",
    emoji: "🇧🇬",
    dialCode: "+359",
  },
  {
    name: "Bahrain",
    code: "BH",
    unicode: "U+1F1E7 U+1F1ED",
    emoji: "🇧🇭",
    dialCode: "+973",
  },
  {
    name: "Bahamas",
    code: "BS",
    unicode: "U+1F1E7 U+1F1F8",
    emoji: "🇧🇸",
    dialCode: "+1-242",
  },
  {
    name: "Bosnia and Herzegovina",
    code: "BA",
    unicode: "U+1F1E7 U+1F1E6",
    emoji: "🇧🇦",
    dialCode: "+387",
  },
  {
    name: "Saint Barthélemy",
    code: "BL",
    unicode: "U+1F1E7 U+1F1F1",
    emoji: "🇧🇱",
    dialCode: "+590",
  },
  {
    name: "Belarus",
    code: "BY",
    unicode: "U+1F1E7 U+1F1FE",
    emoji: "🇧🇾",
    dialCode: "+375",
  },
  {
    name: "Belize",
    code: "BZ",
    unicode: "U+1F1E7 U+1F1FF",
    emoji: "🇧🇿",
    dialCode: "+501",
  },
  {
    name: "Bermuda",
    code: "BM",
    unicode: "U+1F1E7 U+1F1F2",
    emoji: "🇧🇲",
    dialCode: "+1-441",
  },
  {
    name: "Bolivia, Plurinational State of",
    code: "BO",
    unicode: "U+1F1E7 U+1F1F4",
    emoji: "🇧🇴",
    dialCode: "+591",
  },
  {
    name: "Brazil",
    code: "BR",
    unicode: "U+1F1E7 U+1F1F7",
    emoji: "🇧🇷",
    dialCode: "+55",
  },
  {
    name: "Barbados",
    code: "BB",
    unicode: "U+1F1E7 U+1F1E7",
    emoji: "🇧🇧",
    dialCode: "+1-246",
  },
  {
    name: "Brunei Darussalam",
    code: "BN",
    unicode: "U+1F1E7 U+1F1F3",
    emoji: "🇧🇳",
    dialCode: "+673",
  },
  {
    name: "Bhutan",
    code: "BT",
    unicode: "U+1F1E7 U+1F1F9",
    emoji: "🇧🇹",
    dialCode: "+975",
  },
  {
    name: "Bouvet Island",
    code: "BV",
    unicode: "U+1F1E7 U+1F1FB",
    emoji: "🇧🇻",
    dialCode: "+47",
  },
  {
    name: "Botswana",
    code: "BW",
    unicode: "U+1F1E7 U+1F1FC",
    emoji: "🇧🇼",
    dialCode: "+267",
  },
  {
    name: "Central African Republic",
    code: "CF",
    unicode: "U+1F1E8 U+1F1EB",
    emoji: "🇨🇫",
    dialCode: "+236",
  },
  {
    name: "Canada",
    code: "CA",
    unicode: "U+1F1E8 U+1F1E6",
    emoji: "🇨🇦",
    dialCode: "+1",
  },
  {
    name: "Cocos (Keeling) Islands",
    code: "CC",
    unicode: "U+1F1E8 U+1F1E8",
    emoji: "🇨🇨",
    dialCode: "+61",
  },
  {
    name: "Switzerland",
    code: "CH",
    unicode: "U+1F1E8 U+1F1ED",
    emoji: "🇨🇭",
    dialCode: "+41",
  },
  {
    name: "Chile",
    code: "CL",
    unicode: "U+1F1E8 U+1F1F1",
    emoji: "🇨🇱",
    dialCode: "+56",
  },
  {
    name: "China",
    code: "CN",
    unicode: "U+1F1E8 U+1F1F3",
    emoji: "🇨🇳",
    dialCode: "+86",
  },
  {
    name: "Côte d'Ivoire",
    code: "CI",
    unicode: "U+1F1E8 U+1F1EE",
    emoji: "🇨🇮",
    dialCode: "+225",
  },
  {
    name: "Cameroon",
    code: "CM",
    unicode: "U+1F1E8 U+1F1F2",
    emoji: "🇨🇲",
    dialCode: "+237",
  },
  {
    name: "Congo, The Democratic Republic of the",
    code: "CD",
    unicode: "U+1F1E8 U+1F1E9",
    emoji: "🇨🇩",
    dialCode: "+243",
  },
  {
    name: "Congo",
    code: "CG",
    unicode: "U+1F1E8 U+1F1EC",
    emoji: "🇨🇬",
    dialCode: "+242",
  },
  {
    name: "Cook Islands",
    code: "CK",
    unicode: "U+1F1E8 U+1F1F0",
    emoji: "🇨🇰",
    dialCode: "+682",
  },
  {
    name: "Colombia",
    code: "CO",
    unicode: "U+1F1E8 U+1F1F4",
    emoji: "🇨🇴",
    dialCode: "+57",
  },
  {
    name: "Comoros",
    code: "KM",
    unicode: "U+1F1F0 U+1F1F2",
    emoji: "🇰🇲",
    dialCode: "+269",
  },
  {
    name: "Cabo Verde",
    code: "CV",
    unicode: "U+1F1E8 U+1F1FB",
    emoji: "🇨🇻",
    dialCode: "+238",
  },
  {
    name: "Costa Rica",
    code: "CR",
    unicode: "U+1F1E8 U+1F1F7",
    emoji: "🇨🇷",
    dialCode: "+506",
  },
  {
    name: "Cuba",
    code: "CU",
    unicode: "U+1F1E8 U+1F1FA",
    emoji: "🇨🇺",
    dialCode: "+53",
  },
  {
    name: "Curaçao",
    code: "CW",
    unicode: "U+1F1E8 U+1F1FC",
    emoji: "🇨🇼",
    dialCode: "+599",
  },
  {
    name: "Christmas Island",
    code: "CX",
    unicode: "U+1F1E8 U+1F1FD",
    emoji: "🇨🇽",
    dialCode: "+61",
  },
  {
    name: "Cayman Islands",
    code: "KY",
    unicode: "U+1F1F0 U+1F1FE",
    emoji: "🇰🇾",
    dialCode: "+1-345",
  },
  {
    name: "Cyprus",
    code: "CY",
    unicode: "U+1F1E8 U+1F1FE",
    emoji: "🇨🇾",
    dialCode: "+357",
  },
  {
    name: "Czechia",
    code: "CZ",
    unicode: "U+1F1E8 U+1F1FF",
    emoji: "🇨🇿",
    dialCode: "+420",
  },
  {
    name: "Germany",
    code: "DE",
    unicode: "U+1F1E9 U+1F1EA",
    emoji: "🇩🇪",
    dialCode: "+49",
  },
  {
    name: "Djibouti",
    code: "DJ",
    unicode: "U+1F1E9 U+1F1EF",
    emoji: "🇩🇯",
    dialCode: "+253",
  },
  {
    name: "Dominica",
    code: "DM",
    unicode: "U+1F1E9 U+1F1F2",
    emoji: "🇩🇲",
    dialCode: "+1-767",
  },
  {
    name: "Denmark",
    code: "DK",
    unicode: "U+1F1E9 U+1F1F0",
    emoji: "🇩🇰",
    dialCode: "+45",
  },
  {
    name: "Dominican Republic",
    code: "DO",
    unicode: "U+1F1E9 U+1F1F4",
    emoji: "🇩🇴",
    dialCode: "+1-809",
  },
  {
    name: "Algeria",
    code: "DZ",
    unicode: "U+1F1E9 U+1F1FF",
    emoji: "🇩🇿",
    dialCode: "+213",
  },
  {
    name: "Ecuador",
    code: "EC",
    unicode: "U+1F1EA U+1F1E8",
    emoji: "🇪🇨",
    dialCode: "+593",
  },
  {
    name: "Egypt",
    code: "EG",
    unicode: "U+1F1EA U+1F1EC",
    emoji: "🇪🇬",
    dialCode: "+20",
  },
  {
    name: "Eritrea",
    code: "ER",
    unicode: "U+1F1EA U+1F1F7",
    emoji: "🇪🇷",
    dialCode: "+291",
  },
  {
    name: "Western Sahara",
    code: "EH",
    unicode: "U+1F1EA U+1F1ED",
    emoji: "🇪🇭",
    dialCode: "+212",
  },
  {
    name: "Spain",
    code: "ES",
    unicode: "U+1F1EA U+1F1F8",
    emoji: "🇪🇸",
    dialCode: "+34",
  },
  {
    name: "Estonia",
    code: "EE",
    unicode: "U+1F1EA U+1F1EA",
    emoji: "🇪🇪",
    dialCode: "+372",
  },
  {
    name: "Ethiopia",
    code: "ET",
    unicode: "U+1F1EA U+1F1F9",
    emoji: "🇪🇹",
    dialCode: "+251",
  },
  {
    name: "Finland",
    code: "FI",
    unicode: "U+1F1EB U+1F1EE",
    emoji: "🇫🇮",
    dialCode: "+358",
  },
  {
    name: "Fiji",
    code: "FJ",
    unicode: "U+1F1EB U+1F1EF",
    emoji: "🇫🇯",
    dialCode: "+679",
  },
  {
    name: "Falkland Islands (Malvinas)",
    code: "FK",
    unicode: "U+1F1EB U+1F1F0",
    emoji: "🇫🇰",
    dialCode: "+500",
  },
  {
    name: "France",
    code: "FR",
    unicode: "U+1F1EB U+1F1F7",
    emoji: "🇫🇷",
    dialCode: "+33",
  },
  {
    name: "Faroe Islands",
    code: "FO",
    unicode: "U+1F1EB U+1F1F4",
    emoji: "🇫🇴",
    dialCode: "+298",
  },
  {
    name: "Micronesia, Federated States of",
    code: "FM",
    unicode: "U+1F1EB U+1F1F2",
    emoji: "🇫🇲",
    dialCode: "+691",
  },
  {
    name: "Gabon",
    code: "GA",
    unicode: "U+1F1EC U+1F1E6",
    emoji: "🇬🇦",
    dialCode: "+241",
  },
  {
    name: "United Kingdom",
    code: "GB",
    unicode: "U+1F1EC U+1F1E7",
    emoji: "🇬🇧",
    dialCode: "+44",
  },
  {
    name: "Georgia",
    code: "GE",
    unicode: "U+1F1EC U+1F1EA",
    emoji: "🇬🇪",
    dialCode: "+995",
  },
  {
    name: "Guernsey",
    code: "GG",
    unicode: "U+1F1EC U+1F1EC",
    emoji: "🇬🇬",
    dialCode: "+44",
  },
  {
    name: "Ghana",
    code: "GH",
    unicode: "U+1F1EC U+1F1ED",
    emoji: "🇬🇭",
    dialCode: "+233",
  },
  {
    name: "Gibraltar",
    code: "GI",
    unicode: "U+1F1EC U+1F1EE",
    emoji: "🇬🇮",
    dialCode: "+350",
  },
  {
    name: "Guinea",
    code: "GN",
    unicode: "U+1F1EC U+1F1F3",
    emoji: "🇬🇳",
    dialCode: "+224",
  },
  {
    name: "Guadeloupe",
    code: "GP",
    unicode: "U+1F1EC U+1F1F5",
    emoji: "🇬🇵",
    dialCode: "+590",
  },
  {
    name: "Gambia",
    code: "GM",
    unicode: "U+1F1EC U+1F1F2",
    emoji: "🇬🇲",
    dialCode: "+220",
  },
  {
    name: "Guinea-Bissau",
    code: "GW",
    unicode: "U+1F1EC U+1F1FC",
    emoji: "🇬🇼",
    dialCode: "+245",
  },
  {
    name: "Equatorial Guinea",
    code: "GQ",
    unicode: "U+1F1EC U+1F1F6",
    emoji: "🇬🇶",
    dialCode: "+240",
  },
  {
    name: "Greece",
    code: "GR",
    unicode: "U+1F1EC U+1F1F7",
    emoji: "🇬🇷",
    dialCode: "+30",
  },
  {
    name: "Grenada",
    code: "GD",
    unicode: "U+1F1EC U+1F1E9",
    emoji: "🇬🇩",
    dialCode: "+1-473",
  },
  {
    name: "Greenland",
    code: "GL",
    unicode: "U+1F1EC U+1F1F1",
    emoji: "🇬🇱",
    dialCode: "+299",
  },
  {
    name: "Guatemala",
    code: "GT",
    unicode: "U+1F1EC U+1F1F9",
    emoji: "🇬🇹",
    dialCode: "+502",
  },
  {
    name: "French Guiana",
    code: "GF",
    unicode: "U+1F1EC U+1F1EB",
    emoji: "🇬🇫",
    dialCode: "+594",
  },
  {
    name: "Guam",
    code: "GU",
    unicode: "U+1F1EC U+1F1FA",
    emoji: "🇬🇺",
    dialCode: "+1-671",
  },
  {
    name: "Guyana",
    code: "GY",
    unicode: "U+1F1EC U+1F1FE",
    emoji: "🇬🇾",
    dialCode: "+592",
  },
  {
    name: "Hong Kong",
    code: "HK",
    unicode: "U+1F1ED U+1F1F0",
    emoji: "🇭🇰",
    dialCode: "+852",
  },
  {
    name: "Heard Island and McDonald Islands",
    code: "HM",
    unicode: "U+1F1ED U+1F1F2",
    emoji: "🇭🇲",
    dialCode: "+672",
  },
  {
    name: "Honduras",
    code: "HN",
    unicode: "U+1F1ED U+1F1F3",
    emoji: "🇭🇳",
    dialCode: "+504",
  },
  {
    name: "Croatia",
    code: "HR",
    unicode: "U+1F1ED U+1F1F7",
    emoji: "🇭🇷",
    dialCode: "+385",
  },
  {
    name: "Haiti",
    code: "HT",
    unicode: "U+1F1ED U+1F1F9",
    emoji: "🇭🇹",
    dialCode: "+509",
  },
  {
    name: "Hungary",
    code: "HU",
    unicode: "U+1F1ED U+1F1FA",
    emoji: "🇭🇺",
    dialCode: "+36",
  },
  {
    name: "Indonesia",
    code: "ID",
    unicode: "U+1F1EE U+1F1E9",
    emoji: "🇮🇩",
    dialCode: "+62",
  },
  {
    name: "Isle of Man",
    code: "IM",
    unicode: "U+1F1EE U+1F1F2",
    emoji: "🇮🇲",
    dialCode: "+44",
  },
  {
    name: "India",
    code: "IN",
    unicode: "U+1F1EE U+1F1F3",
    emoji: "🇮🇳",
    dialCode: "+91",
  },
  {
    name: "British Indian Ocean Territory",
    code: "IO",
    unicode: "U+1F1EE U+1F1F4",
    emoji: "🇮🇴",
    dialCode: "+246",
  },
  {
    name: "Ireland",
    code: "IE",
    unicode: "U+1F1EE U+1F1EA",
    emoji: "🇮🇪",
    dialCode: "+353",
  },
  {
    name: "Iran, Islamic Republic of",
    code: "IR",
    unicode: "U+1F1EE U+1F1F7",
    emoji: "🇮🇷",
    dialCode: "+98",
  },
  {
    name: "Iraq",
    code: "IQ",
    unicode: "U+1F1EE U+1F1F6",
    emoji: "🇮🇶",
    dialCode: "+964",
  },
  {
    name: "Iceland",
    code: "IS",
    unicode: "U+1F1EE U+1F1F8",
    emoji: "🇮🇸",
    dialCode: "+354",
  },
  {
    name: "Israel",
    code: "IL",
    unicode: "U+1F1EE U+1F1F1",
    emoji: "🇮🇱",
    dialCode: "+972",
  },
  {
    name: "Italy",
    code: "IT",
    unicode: "U+1F1EE U+1F1F9",
    emoji: "🇮🇹",
    dialCode: "+39",
  },
  {
    name: "Jamaica",
    code: "JM",
    unicode: "U+1F1EF U+1F1F2",
    emoji: "🇯🇲",
    dialCode: "+1-876",
  },
  {
    name: "Jersey",
    code: "JE",
    unicode: "U+1F1EF U+1F1EA",
    emoji: "🇯🇪",
    dialCode: "+44",
  },
  {
    name: "Jordan",
    code: "JO",
    unicode: "U+1F1EF U+1F1F4",
    emoji: "🇯🇴",
    dialCode: "+962",
  },
  {
    name: "Japan",
    code: "JP",
    unicode: "U+1F1EF U+1F1F5",
    emoji: "🇯🇵",
    dialCode: "+81",
  },
  {
    name: "Kazakhstan",
    code: "KZ",
    unicode: "U+1F1F0 U+1F1FF",
    emoji: "🇰🇿",
    dialCode: "+7",
  },
  {
    name: "Kenya",
    code: "KE",
    unicode: "U+1F1F0 U+1F1EA",
    emoji: "🇰🇪",
    dialCode: "+254",
  },
  {
    name: "Kyrgyzstan",
    code: "KG",
    unicode: "U+1F1F0 U+1F1EC",
    emoji: "🇰🇬",
    dialCode: "+996",
  },
  {
    name: "Cambodia",
    code: "KH",
    unicode: "U+1F1F0 U+1F1ED",
    emoji: "🇰🇭",
    dialCode: "+855",
  },
  {
    name: "Kiribati",
    code: "KI",
    unicode: "U+1F1F0 U+1F1EE",
    emoji: "🇰🇮",
    dialCode: "+686",
  },
  {
    name: "Saint Kitts and Nevis",
    code: "KN",
    unicode: "U+1F1F0 U+1F1F3",
    emoji: "🇰🇳",
    dialCode: "+1-869",
  },
  {
    name: "Korea, Republic of",
    code: "KR",
    unicode: "U+1F1F0 U+1F1F7",
    emoji: "🇰🇷",
    dialCode: "+82",
  },
  {
    name: "Kuwait",
    code: "KW",
    unicode: "U+1F1F0 U+1F1FC",
    emoji: "🇰🇼",
    dialCode: "+965",
  },
  {
    name: "Lao People's Democratic Republic",
    code: "LA",
    unicode: "U+1F1F1 U+1F1E6",
    emoji: "🇱🇦",
    dialCode: "+856",
  },
  {
    name: "Lebanon",
    code: "LB",
    unicode: "U+1F1F1 U+1F1E7",
    emoji: "🇱🇧",
    dialCode: "+961",
  },
  {
    name: "Liberia",
    code: "LR",
    unicode: "U+1F1F1 U+1F1F7",
    emoji: "🇱🇷",
    dialCode: "+231",
  },
  {
    name: "Libya",
    code: "LY",
    unicode: "U+1F1F1 U+1F1FE",
    emoji: "🇱🇾",
    dialCode: "+218",
  },
  {
    name: "Saint Lucia",
    code: "LC",
    unicode: "U+1F1F1 U+1F1E8",
    emoji: "🇱🇨",
    dialCode: "+1-758",
  },
  {
    name: "Liechtenstein",
    code: "LI",
    unicode: "U+1F1F1 U+1F1EE",
    emoji: "🇱🇮",
    dialCode: "+423",
  },
  {
    name: "Sri Lanka",
    code: "LK",
    unicode: "U+1F1F1 U+1F1F0",
    emoji: "🇱🇰",
    dialCode: "+94",
  },
  {
    name: "Lesotho",
    code: "LS",
    unicode: "U+1F1F1 U+1F1F8",
    emoji: "🇱🇸",
    dialCode: "+266",
  },
  {
    name: "Lithuania",
    code: "LT",
    unicode: "U+1F1F1 U+1F1F9",
    emoji: "🇱🇹",
    dialCode: "+370",
  },
  {
    name: "Luxembourg",
    code: "LU",
    unicode: "U+1F1F1 U+1F1FA",
    emoji: "🇱🇺",
    dialCode: "+352",
  },
  {
    name: "Latvia",
    code: "LV",
    unicode: "U+1F1F1 U+1F1FB",
    emoji: "🇱🇻",
    dialCode: "+371",
  },
  {
    name: "Macao",
    code: "MO",
    unicode: "U+1F1F2 U+1F1F4",
    emoji: "🇲🇴",
    dialCode: "+853",
  },
  {
    name: "Saint Martin (French part)",
    code: "MF",
    unicode: "U+1F1F2 U+1F1EB",
    emoji: "🇲🇫",
    dialCode: "+590",
  },
  {
    name: "Morocco",
    code: "MA",
    unicode: "U+1F1F2 U+1F1E6",
    emoji: "🇲🇦",
    dialCode: "+212",
  },
  {
    name: "Monaco",
    code: "MC",
    unicode: "U+1F1F2 U+1F1E8",
    emoji: "🇲🇨",
    dialCode: "+377",
  },
  {
    name: "Moldova, Republic of",
    code: "MD",
    unicode: "U+1F1F2 U+1F1E9",
    emoji: "🇲🇩",
    dialCode: "+373",
  },
  {
    name: "Madagascar",
    code: "MG",
    unicode: "U+1F1F2 U+1F1EC",
    emoji: "🇲🇬",
    dialCode: "+261",
  },
  {
    name: "Maldives",
    code: "MV",
    unicode: "U+1F1F2 U+1F1FB",
    emoji: "🇲🇻",
    dialCode: "+960",
  },
  {
    name: "Mexico",
    code: "MX",
    unicode: "U+1F1F2 U+1F1FD",
    emoji: "🇲🇽",
    dialCode: "+52",
  },
  {
    name: "Marshall Islands",
    code: "MH",
    unicode: "U+1F1F2 U+1F1ED",
    emoji: "🇲🇭",
    dialCode: "+692",
  },
  {
    name: "North Macedonia",
    code: "MK",
    unicode: "U+1F1F2 U+1F1F0",
    emoji: "🇲🇰",
    dialCode: "+389",
  },
  {
    name: "Mali",
    code: "ML",
    unicode: "U+1F1F2 U+1F1F1",
    emoji: "🇲🇱",
    dialCode: "+223",
  },
  {
    name: "Malta",
    code: "MT",
    unicode: "U+1F1F2 U+1F1F9",
    emoji: "🇲🇹",
    dialCode: "+356",
  },
  {
    name: "Myanmar",
    code: "MM",
    unicode: "U+1F1F2 U+1F1F2",
    emoji: "🇲🇲",
    dialCode: "+95",
  },
  {
    name: "Montenegro",
    code: "ME",
    unicode: "U+1F1F2 U+1F1EA",
    emoji: "🇲🇪",
    dialCode: "+382",
  },
  {
    name: "Mongolia",
    code: "MN",
    unicode: "U+1F1F2 U+1F1F3",
    emoji: "🇲🇳",
    dialCode: "+976",
  },
  {
    name: "Northern Mariana Islands",
    code: "MP",
    unicode: "U+1F1F2 U+1F1F5",
    emoji: "🇲🇵",
    dialCode: "+1-670",
  },
  {
    name: "Mozambique",
    code: "MZ",
    unicode: "U+1F1F2 U+1F1FF",
    emoji: "🇲🇿",
    dialCode: "+258",
  },
  {
    name: "Mauritania",
    code: "MR",
    unicode: "U+1F1F2 U+1F1F7",
    emoji: "🇲🇷",
    dialCode: "+222",
  },
  {
    name: "Montserrat",
    code: "MS",
    unicode: "U+1F1F2 U+1F1F8",
    emoji: "🇲🇸",
    dialCode: "+1-664",
  },
  {
    name: "Martinique",
    code: "MQ",
    unicode: "U+1F1F2 U+1F1F6",
    emoji: "🇲🇶",
    dialCode: "+596",
  },
  {
    name: "Mauritius",
    code: "MU",
    unicode: "U+1F1F2 U+1F1FA",
    emoji: "🇲🇺",
    dialCode: "+230",
  },
  {
    name: "Malawi",
    code: "MW",
    unicode: "U+1F1F2 U+1F1FC",
    emoji: "🇲🇼",
    dialCode: "+265",
  },
  {
    name: "Malaysia",
    code: "MY",
    unicode: "U+1F1F2 U+1F1FE",
    emoji: "🇲🇾",
    dialCode: "+60",
  },
  {
    name: "Mayotte",
    code: "YT",
    unicode: "U+1F1FE U+1F1F9",
    emoji: "🇾🇹",
    dialCode: "+262",
  },
  {
    name: "Namibia",
    code: "NA",
    unicode: "U+1F1F3 U+1F1E6",
    emoji: "🇳🇦",
    dialCode: "+264",
  },
  {
    name: "New Caledonia",
    code: "NC",
    unicode: "U+1F1F3 U+1F1E8",
    emoji: "🇳🇨",
    dialCode: "+687",
  },
  {
    name: "Niger",
    code: "NE",
    unicode: "U+1F1F3 U+1F1EA",
    emoji: "🇳🇪",
    dialCode: "+227",
  },
  {
    name: "Norfolk Island",
    code: "NF",
    unicode: "U+1F1F3 U+1F1EB",
    emoji: "🇳🇫",
    dialCode: "+672",
  },
  {
    name: "Nigeria",
    code: "NG",
    unicode: "U+1F1F3 U+1F1EC",
    emoji: "🇳🇬",
    dialCode: "+234",
  },
  {
    name: "Nicaragua",
    code: "NI",
    unicode: "U+1F1F3 U+1F1EE",
    emoji: "🇳🇮",
    dialCode: "+505",
  },
  {
    name: "Niue",
    code: "NU",
    unicode: "U+1F1F3 U+1F1FA",
    emoji: "🇳🇺",
    dialCode: "+683",
  },
  {
    name: "Netherlands",
    code: "NL",
    unicode: "U+1F1F3 U+1F1F1",
    emoji: "🇳🇱",
    dialCode: "+31",
  },
  {
    name: "Norway",
    code: "NO",
    unicode: "U+1F1F3 U+1F1F4",
    emoji: "🇳🇴",
    dialCode: "+47",
  },
  {
    name: "Nepal",
    code: "NP",
    unicode: "U+1F1F3 U+1F1F5",
    emoji: "🇳🇵",
    dialCode: "+977",
  },
  {
    name: "Nauru",
    code: "NR",
    unicode: "U+1F1F3 U+1F1F7",
    emoji: "🇳🇷",
    dialCode: "+674",
  },
  {
    name: "New Zealand",
    code: "NZ",
    unicode: "U+1F1F3 U+1F1FF",
    emoji: "🇳🇿",
    dialCode: "+64",
  },
  {
    name: "Oman",
    code: "OM",
    unicode: "U+1F1F4 U+1F1F2",
    emoji: "🇴🇲",
    dialCode: "+968",
  },
  {
    name: "Pakistan",
    code: "PK",
    unicode: "U+1F1F5 U+1F1F0",
    emoji: "🇵🇰",
    dialCode: "+92",
  },
  {
    name: "Panama",
    code: "PA",
    unicode: "U+1F1F5 U+1F1E6",
    emoji: "🇵🇦",
    dialCode: "+507",
  },
  {
    name: "Pitcairn",
    code: "PN",
    unicode: "U+1F1F5 U+1F1F3",
    emoji: "🇵🇳",
    dialCode: "+64",
  },
  {
    name: "Peru",
    code: "PE",
    unicode: "U+1F1F5 U+1F1EA",
    emoji: "🇵🇪",
    dialCode: "+51",
  },
  {
    name: "Philippines",
    code: "PH",
    unicode: "U+1F1F5 U+1F1ED",
    emoji: "🇵🇭",
    dialCode: "+63",
  },
  {
    name: "Palau",
    code: "PW",
    unicode: "U+1F1F5 U+1F1FC",
    emoji: "🇵🇼",
    dialCode: "+680",
  },
  {
    name: "Papua New Guinea",
    code: "PG",
    unicode: "U+1F1F5 U+1F1EC",
    emoji: "🇵🇬",
    dialCode: "+675",
  },
  {
    name: "Poland",
    code: "PL",
    unicode: "U+1F1F5 U+1F1F1",
    emoji: "🇵🇱",
    dialCode: "+48",
  },
  {
    name: "Puerto Rico",
    code: "PR",
    unicode: "U+1F1F5 U+1F1F7",
    emoji: "🇵🇷",
    dialCode: "+1-787 / +1-939",
  },
  {
    name: "Korea, Democratic People's Republic of",
    code: "KP",
    unicode: "U+1F1F0 U+1F1F5",
    emoji: "🇰🇵",
    dialCode: "+850",
  },
  {
    name: "Portugal",
    code: "PT",
    unicode: "U+1F1F5 U+1F1F9",
    emoji: "🇵🇹",
    dialCode: "+351",
  },
  {
    name: "Paraguay",
    code: "PY",
    unicode: "U+1F1F5 U+1F1FE",
    emoji: "🇵🇾",
    dialCode: "+595",
  },
  {
    name: "Palestine, State of",
    code: "PS",
    unicode: "U+1F1F5 U+1F1F8",
    emoji: "🇵🇸",
    dialCode: "+970",
  },
  {
    name: "French Polynesia",
    code: "PF",
    unicode: "U+1F1F5 U+1F1EB",
    emoji: "🇵🇫",
    dialCode: "+689",
  },
  {
    name: "Qatar",
    code: "QA",
    unicode: "U+1F1F6 U+1F1E6",
    emoji: "🇶🇦",
    dialCode: "+974",
  },
  {
    name: "Réunion",
    code: "RE",
    unicode: "U+1F1F7 U+1F1EA",
    emoji: "🇷🇪",
    dialCode: "+262",
  },
  {
    name: "Romania",
    code: "RO",
    unicode: "U+1F1F7 U+1F1F4",
    emoji: "🇷🇴",
    dialCode: "+40",
  },
  {
    name: "Russian Federation",
    code: "RU",
    unicode: "U+1F1F7 U+1F1FA",
    emoji: "🇷🇺",
    dialCode: "+7",
  },
  {
    name: "Rwanda",
    code: "RW",
    unicode: "U+1F1F7 U+1F1FC",
    emoji: "🇷🇼",
    dialCode: "+250",
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    unicode: "U+1F1F8 U+1F1E6",
    emoji: "🇸🇦",
    dialCode: "+966",
  },
  {
    name: "Sudan",
    code: "SD",
    unicode: "U+1F1F8 U+1F1E9",
    emoji: "🇸🇩",
    dialCode: "+249",
  },
  {
    name: "Senegal",
    code: "SN",
    unicode: "U+1F1F8 U+1F1F3",
    emoji: "🇸🇳",
    dialCode: "+221",
  },
  {
    name: "Singapore",
    code: "SG",
    unicode: "U+1F1F8 U+1F1EC",
    emoji: "🇸🇬",
    dialCode: "+65",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    code: "GS",
    unicode: "U+1F1EC U+1F1F8",
    emoji: "🇬🇸",
    dialCode: "+500",
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    code: "SH",
    unicode: "U+1F1F8 U+1F1ED",
    emoji: "🇸🇭",
    dialCode: "+290",
  },
  {
    name: "Svalbard and Jan Mayen",
    code: "SJ",
    unicode: "U+1F1F8 U+1F1EF",
    emoji: "🇸🇯",
    dialCode: "+47",
  },

  {
    name: "Solomon Islands",
    code: "SB",
    unicode: "U+1F1F8 U+1F1E7",
    emoji: "🇸🇧",
    dialCode: "+677",
  },
  {
    name: "Seychelles",
    code: "SC",
    unicode: "U+1F1F8 U+1F1E8",
    emoji: "🇸🇨",
    dialCode: "+248",
  },
  {
    name: "Sudan",
    code: "SD",
    unicode: "U+1F1F8 U+1F1E9",
    emoji: "🇸🇩",
    dialCode: "+249",
  },
  {
    name: "Sweden",
    code: "SE",
    unicode: "U+1F1F8 U+1F1EA",
    emoji: "🇸🇪",
    dialCode: "+46",
  },
  {
    name: "Singapore",
    code: "SG",
    unicode: "U+1F1F8 U+1F1EC",
    emoji: "🇸🇬",
    dialCode: "+65",
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    code: "SH",
    unicode: "U+1F1F8 U+1F1ED",
    emoji: "🇸🇭",
    dialCode: "+290",
  },
  {
    name: "Slovenia",
    code: "SI",
    unicode: "U+1F1F8 U+1F1EE",
    emoji: "🇸🇮",
    dialCode: "+386",
  },
  {
    name: "Svalbard and Jan Mayen",
    code: "SJ",
    unicode: "U+1F1F8 U+1F1EF",
    emoji: "🇸🇯",
    dialCode: "+47",
  },
  {
    name: "Slovakia",
    code: "SK",
    unicode: "U+1F1F8 U+1F1F0",
    emoji: "🇸🇰",
    dialCode: "+421",
  },
  {
    name: "Sierra Leone",
    code: "SL",
    unicode: "U+1F1F8 U+1F1F1",
    emoji: "🇸🇱",
    dialCode: "+232",
  },
  {
    name: "San Marino",
    code: "SM",
    unicode: "U+1F1F8 U+1F1F2",
    emoji: "🇸🇲",
    dialCode: "+378",
  },
  {
    name: "Senegal",
    code: "SN",
    unicode: "U+1F1F8 U+1F1F3",
    emoji: "🇸🇳",
    dialCode: "+221",
  },
  {
    name: "Somalia",
    code: "SO",
    unicode: "U+1F1F8 U+1F1F4",
    emoji: "🇸🇴",
    dialCode: "+252",
  },
  {
    name: "Suriname",
    code: "SR",
    unicode: "U+1F1F8 U+1F1F7",
    emoji: "🇸🇷",
    dialCode: "+597",
  },
  {
    name: "South Sudan",
    code: "SS",
    unicode: "U+1F1F8 U+1F1F8",
    emoji: "🇸🇸",
    dialCode: "+211",
  },
  {
    name: "Sao Tome and Principe",
    code: "ST",
    unicode: "U+1F1F8 U+1F1F9",
    emoji: "🇸🇹",
    dialCode: "+239",
  },
  {
    name: "El Salvador",
    code: "SV",
    unicode: "U+1F1F8 U+1F1FB",
    emoji: "🇸🇻",
    dialCode: "+503",
  },
  {
    name: "Sint Maarten (Dutch part)",
    code: "SX",
    unicode: "U+1F1F8 U+1F1FD",
    emoji: "🇸🇽",
    dialCode: "+1-721",
  },
  {
    name: "Syrian Arab Republic",
    code: "SY",
    unicode: "U+1F1F8 U+1F1FE",
    emoji: "🇸🇾",
    dialCode: "+963",
  },
  {
    name: "Eswatini",
    code: "SZ",
    unicode: "U+1F1F8 U+1F1FF",
    emoji: "🇸🇿",
    dialCode: "+268",
  },
  {
    name: "Sint Maarten (Dutch part)",
    code: "SX",
    unicode: "U+1F1F8 U+1F1FD",
    emoji: "🇸🇽",
    dialCode: "+1-721",
  },
  {
    name: "Seychelles",
    code: "SC",
    unicode: "U+1F1F8 U+1F1E8",
    emoji: "🇸🇨",
    dialCode: "+248",
  },
  {
    name: "Syrian Arab Republic",
    code: "SY",
    unicode: "U+1F1F8 U+1F1FE",
    emoji: "🇸🇾",
    dialCode: "+963",
  },
  {
    name: "Turks and Caicos Islands",
    code: "TC",
    unicode: "U+1F1F9 U+1F1E8",
    emoji: "🇹🇨",
    dialCode: "+1-649",
  },
  {
    name: "Chad",
    code: "TD",
    unicode: "U+1F1F9 U+1F1E9",
    emoji: "🇹🇩",
    dialCode: "+235",
  },
  {
    name: "Togo",
    code: "TG",
    unicode: "U+1F1F9 U+1F1EC",
    emoji: "🇹🇬",
    dialCode: "+228",
  },
  {
    name: "Thailand",
    code: "TH",
    unicode: "U+1F1F9 U+1F1ED",
    emoji: "🇹🇭",
    dialCode: "+66",
  },
  {
    name: "Tajikistan",
    code: "TJ",
    unicode: "U+1F1F9 U+1F1EF",
    emoji: "🇹🇯",
    dialCode: "+992",
  },
  {
    name: "Tokelau",
    code: "TK",
    unicode: "U+1F1F9 U+1F1F0",
    emoji: "🇹🇰",
    dialCode: "+690",
  },
  {
    name: "Turkmenistan",
    code: "TM",
    unicode: "U+1F1F9 U+1F1F2",
    emoji: "🇹🇲",
    dialCode: "+993",
  },
  {
    name: "Timor-Leste",
    code: "TL",
    unicode: "U+1F1F9 U+1F1F1",
    emoji: "🇹🇱",
    dialCode: "+670",
  },
  {
    name: "Tonga",
    code: "TO",
    unicode: "U+1F1F9 U+1F1F4",
    emoji: "🇹🇴",
    dialCode: "+676",
  },
  {
    name: "Trinidad and Tobago",
    code: "TT",
    unicode: "U+1F1F9 U+1F1F9",
    emoji: "🇹🇹",
    dialCode: "+1-868",
  },
  {
    name: "Tunisia",
    code: "TN",
    unicode: "U+1F1F9 U+1F1F3",
    emoji: "🇹🇳",
    dialCode: "+216",
  },
  {
    name: "Turkey",
    code: "TR",
    unicode: "U+1F1F9 U+1F1F7",
    emoji: "🇹🇷",
    dialCode: "+90",
  },
  {
    name: "Tuvalu",
    code: "TV",
    unicode: "U+1F1F9 U+1F1FB",
    emoji: "🇹🇻",
    dialCode: "+688",
  },
  {
    name: "Taiwan, Province of China",
    code: "TW",
    unicode: "U+1F1F9 U+1F1FC",
    emoji: "🇹🇼",
    dialCode: "+886",
  },
  {
    name: "Tanzania, United Republic of",
    code: "TZ",
    unicode: "U+1F1F9 U+1F1FF",
    emoji: "🇹🇿",
    dialCode: "+255",
  },
  {
    name: "Uganda",
    code: "UG",
    unicode: "U+1F1FA U+1F1EC",
    emoji: "🇺🇬",
    dialCode: "+256",
  },
  {
    name: "Ukraine",
    code: "UA",
    unicode: "U+1F1FA U+1F1E6",
    emoji: "🇺🇦",
    dialCode: "+380",
  },
  {
    name: "United States Minor Outlying Islands",
    code: "UM",
    unicode: "U+1F1FA U+1F1F2",
    emoji: "🇺🇲",
    dialCode: "",
  },
  {
    name: "Uruguay",
    code: "UY",
    unicode: "U+1F1FA U+1F1FE",
    emoji: "🇺🇾",
    dialCode: "+598",
  },
  {
    name: "United States",
    code: "US",
    unicode: "U+1F1FA U+1F1F8",
    emoji: "🇺🇸",
    dialCode: "+1",
  },
  {
    name: "Uzbekistan",
    code: "UZ",
    unicode: "U+1F1FA U+1F1FF",
    emoji: "🇺🇿",
    dialCode: "+998",
  },
  {
    name: "Holy See (Vatican City State)",
    code: "VA",
    unicode: "U+1F1FB U+1F1E6",
    emoji: "🇻🇦",
    dialCode: "+379",
  },
  {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    unicode: "U+1F1FB U+1F1E8",
    emoji: "🇻🇨",
    dialCode: "+1-784",
  },
  {
    name: "Venezuela, Bolivarian Republic of",
    code: "VE",
    unicode: "U+1F1FB U+1F1EA",
    emoji: "🇻🇪",
    dialCode: "+58",
  },
  {
    name: "Virgin Islands, British",
    code: "VG",
    unicode: "U+1F1FB U+1F1EC",
    emoji: "🇻🇬",
    dialCode: "+1-284",
  },
  {
    name: "Virgin Islands, U.S.",
    code: "VI",
    unicode: "U+1F1FB U+1F1EE",
    emoji: "🇻🇮",
    dialCode: "+1-340",
  },
  {
    name: "Viet Nam",
    code: "VN",
    unicode: "U+1F1FB U+1F1F3",
    emoji: "🇻🇳",
    dialCode: "+84",
  },
  {
    name: "Vanuatu",
    code: "VU",
    unicode: "U+1F1FB U+1F1FA",
    emoji: "🇻🇺",
    dialCode: "+678",
  },
  {
    name: "Wallis and Futuna",
    code: "WF",
    unicode: "U+1F1FC U+1F1EB",
    emoji: "🇼🇫",
    dialCode: "+681",
  },
  {
    name: "Samoa",
    code: "WS",
    unicode: "U+1F1FC U+1F1F8",
    emoji: "🇼🇸",
    dialCode: "+685",
  },
  {
    name: "Yemen",
    code: "YE",
    unicode: "U+1F1FE U+1F1EA",
    emoji: "🇾🇪",
    dialCode: "+967",
  },
  {
    name: "South Africa",
    code: "ZA",
    unicode: "U+1F1FF U+1F1E6",
    emoji: "🇿🇦",
    dialCode: "+27",
  },
  {
    name: "Zambia",
    code: "ZM",
    unicode: "U+1F1FF U+1F1F2",
    emoji: "🇿🇲",
    dialCode: "+260",
  },
  {
    name: "Zimbabwe",
    code: "ZW",
    unicode: "U+1F1FF U+1F1FC",
    emoji: "🇿🇼",
    dialCode: "+263",
  },
];
