export interface Country {
  name: string;
  code: string;
  unicode: string;
  emoji: string;
}

export const countries: Country[] = [
  { name: "Aruba", code: "AW", unicode: "U+1F1E6 U+1F1FC", emoji: "🇦🇼" },
  { name: "Afghanistan", code: "AF", unicode: "U+1F1E6 U+1F1EB", emoji: "🇦🇫" },
  { name: "Angola", code: "AO", unicode: "U+1F1E6 U+1F1F4", emoji: "🇦🇴" },
  { name: "Anguilla", code: "AI", unicode: "U+1F1E6 U+1F1EE", emoji: "🇦🇮" },
  {
    name: "Åland Islands",
    code: "AX",
    unicode: "U+1F1E6 U+1F1FD",
    emoji: "🇦🇽",
  },
  { name: "Albania", code: "AL", unicode: "U+1F1E6 U+1F1F1", emoji: "🇦🇱" },
  { name: "Andorra", code: "AD", unicode: "U+1F1E6 U+1F1E9", emoji: "🇦🇩" },
  {
    name: "United Arab Emirates",
    code: "AE",
    unicode: "U+1F1E6 U+1F1EA",
    emoji: "🇦🇪",
  },
  { name: "Argentina", code: "AR", unicode: "U+1F1E6 U+1F1F7", emoji: "🇦🇷" },
  { name: "Armenia", code: "AM", unicode: "U+1F1E6 U+1F1F2", emoji: "🇦🇲" },
  {
    name: "American Samoa",
    code: "AS",
    unicode: "U+1F1E6 U+1F1F8",
    emoji: "🇦🇸",
  },
  { name: "Antarctica", code: "AQ", unicode: "U+1F1E6 U+1F1F6", emoji: "🇦🇶" },
  {
    name: "French Southern Territories",
    code: "TF",
    unicode: "U+1F1F9 U+1F1EB",
    emoji: "🇹🇫",
  },
  {
    name: "Antigua and Barbuda",
    code: "AG",
    unicode: "U+1F1E6 U+1F1EC",
    emoji: "🇦🇬",
  },
  { name: "Australia", code: "AU", unicode: "U+1F1E6 U+1F1FA", emoji: "🇦🇺" },
  { name: "Austria", code: "AT", unicode: "U+1F1E6 U+1F1F9", emoji: "🇦🇹" },
  { name: "Azerbaijan", code: "AZ", unicode: "U+1F1E6 U+1F1FF", emoji: "🇦🇿" },
  { name: "Burundi", code: "BI", unicode: "U+1F1E7 U+1F1EE", emoji: "🇧🇮" },
  { name: "Belgium", code: "BE", unicode: "U+1F1E7 U+1F1EA", emoji: "🇧🇪" },
  { name: "Benin", code: "BJ", unicode: "U+1F1E7 U+1F1EF", emoji: "🇧🇯" },
  {
    name: "Bonaire, Sint Eustatius and Saba",
    code: "BQ",
    unicode: "U+1F1E7 U+1F1F6",
    emoji: "🇧🇶",
  },
  { name: "Burkina Faso", code: "BF", unicode: "U+1F1E7 U+1F1EB", emoji: "🇧🇫" },
  { name: "Bangladesh", code: "BD", unicode: "U+1F1E7 U+1F1E9", emoji: "🇧🇩" },
  { name: "Bulgaria", code: "BG", unicode: "U+1F1E7 U+1F1EC", emoji: "🇧🇬" },
  { name: "Bahrain", code: "BH", unicode: "U+1F1E7 U+1F1ED", emoji: "🇧🇭" },
  { name: "Bahamas", code: "BS", unicode: "U+1F1E7 U+1F1F8", emoji: "🇧🇸" },
  {
    name: "Bosnia and Herzegovina",
    code: "BA",
    unicode: "U+1F1E7 U+1F1E6",
    emoji: "🇧🇦",
  },
  {
    name: "Saint Barthélemy",
    code: "BL",
    unicode: "U+1F1E7 U+1F1F1",
    emoji: "🇧🇱",
  },
  { name: "Belarus", code: "BY", unicode: "U+1F1E7 U+1F1FE", emoji: "🇧🇾" },
  { name: "Belize", code: "BZ", unicode: "U+1F1E7 U+1F1FF", emoji: "🇧🇿" },
  { name: "Bermuda", code: "BM", unicode: "U+1F1E7 U+1F1F2", emoji: "🇧🇲" },
  {
    name: "Bolivia, Plurinational State of",
    code: "BO",
    unicode: "U+1F1E7 U+1F1F4",
    emoji: "🇧🇴",
  },
  { name: "Brazil", code: "BR", unicode: "U+1F1E7 U+1F1F7", emoji: "🇧🇷" },
  { name: "Barbados", code: "BB", unicode: "U+1F1E7 U+1F1E7", emoji: "🇧🇧" },
  {
    name: "Brunei Darussalam",
    code: "BN",
    unicode: "U+1F1E7 U+1F1F3",
    emoji: "🇧🇳",
  },
  { name: "Bhutan", code: "BT", unicode: "U+1F1E7 U+1F1F9", emoji: "🇧🇹" },
  {
    name: "Bouvet Island",
    code: "BV",
    unicode: "U+1F1E7 U+1F1FB",
    emoji: "🇧🇻",
  },
  { name: "Botswana", code: "BW", unicode: "U+1F1E7 U+1F1FC", emoji: "🇧🇼" },
  {
    name: "Central African Republic",
    code: "CF",
    unicode: "U+1F1E8 U+1F1EB",
    emoji: "🇨🇫",
  },
  { name: "Canada", code: "CA", unicode: "U+1F1E8 U+1F1E6", emoji: "🇨🇦" },
  {
    name: "Cocos (Keeling) Islands",
    code: "CC",
    unicode: "U+1F1E8 U+1F1E8",
    emoji: "🇨🇨",
  },
  { name: "Switzerland", code: "CH", unicode: "U+1F1E8 U+1F1ED", emoji: "🇨🇭" },
  { name: "Chile", code: "CL", unicode: "U+1F1E8 U+1F1F1", emoji: "🇨🇱" },
  { name: "China", code: "CN", unicode: "U+1F1E8 U+1F1F3", emoji: "🇨🇳" },
  {
    name: "Côte d'Ivoire",
    code: "CI",
    unicode: "U+1F1E8 U+1F1EE",
    emoji: "🇨🇮",
  },
  { name: "Cameroon", code: "CM", unicode: "U+1F1E8 U+1F1F2", emoji: "🇨🇲" },
  {
    name: "Congo, The Democratic Republic of the",
    code: "CD",
    unicode: "U+1F1E8 U+1F1E9",
    emoji: "🇨🇩",
  },
  { name: "Congo", code: "CG", unicode: "U+1F1E8 U+1F1EC", emoji: "🇨🇬" },
  { name: "Cook Islands", code: "CK", unicode: "U+1F1E8 U+1F1F0", emoji: "🇨🇰" },
  { name: "Colombia", code: "CO", unicode: "U+1F1E8 U+1F1F4", emoji: "🇨🇴" },
  { name: "Comoros", code: "KM", unicode: "U+1F1F0 U+1F1F2", emoji: "🇰🇲" },
  { name: "Cabo Verde", code: "CV", unicode: "U+1F1E8 U+1F1FB", emoji: "🇨🇻" },
  { name: "Costa Rica", code: "CR", unicode: "U+1F1E8 U+1F1F7", emoji: "🇨🇷" },
  { name: "Cuba", code: "CU", unicode: "U+1F1E8 U+1F1FA", emoji: "🇨🇺" },
  { name: "Curaçao", code: "CW", unicode: "U+1F1E8 U+1F1FC", emoji: "🇨🇼" },
  {
    name: "Christmas Island",
    code: "CX",
    unicode: "U+1F1E8 U+1F1FD",
    emoji: "🇨🇽",
  },
  {
    name: "Cayman Islands",
    code: "KY",
    unicode: "U+1F1F0 U+1F1FE",
    emoji: "🇰🇾",
  },
  { name: "Cyprus", code: "CY", unicode: "U+1F1E8 U+1F1FE", emoji: "🇨🇾" },
  { name: "Czechia", code: "CZ", unicode: "U+1F1E8 U+1F1FF", emoji: "🇨🇿" },
  { name: "Germany", code: "DE", unicode: "U+1F1E9 U+1F1EA", emoji: "🇩🇪" },
  { name: "Djibouti", code: "DJ", unicode: "U+1F1E9 U+1F1EF", emoji: "🇩🇯" },
  { name: "Dominica", code: "DM", unicode: "U+1F1E9 U+1F1F2", emoji: "🇩🇲" },
  { name: "Denmark", code: "DK", unicode: "U+1F1E9 U+1F1F0", emoji: "🇩🇰" },
  {
    name: "Dominican Republic",
    code: "DO",
    unicode: "U+1F1E9 U+1F1F4",
    emoji: "🇩🇴",
  },
  { name: "Algeria", code: "DZ", unicode: "U+1F1E9 U+1F1FF", emoji: "🇩🇿" },
  { name: "Ecuador", code: "EC", unicode: "U+1F1EA U+1F1E8", emoji: "🇪🇨" },
  { name: "Egypt", code: "EG", unicode: "U+1F1EA U+1F1EC", emoji: "🇪🇬" },
  { name: "Eritrea", code: "ER", unicode: "U+1F1EA U+1F1F7", emoji: "🇪🇷" },
  {
    name: "Western Sahara",
    code: "EH",
    unicode: "U+1F1EA U+1F1ED",
    emoji: "🇪🇭",
  },
  { name: "Spain", code: "ES", unicode: "U+1F1EA U+1F1F8", emoji: "🇪🇸" },
  { name: "Estonia", code: "EE", unicode: "U+1F1EA U+1F1EA", emoji: "🇪🇪" },
  { name: "Ethiopia", code: "ET", unicode: "U+1F1EA U+1F1F9", emoji: "🇪🇹" },
  { name: "Finland", code: "FI", unicode: "U+1F1EB U+1F1EE", emoji: "🇫🇮" },
  { name: "Fiji", code: "FJ", unicode: "U+1F1EB U+1F1EF", emoji: "🇫🇯" },
  {
    name: "Falkland Islands (Malvinas)",
    code: "FK",
    unicode: "U+1F1EB U+1F1F0",
    emoji: "🇫🇰",
  },
  { name: "France", code: "FR", unicode: "U+1F1EB U+1F1F7", emoji: "🇫🇷" },
  {
    name: "Faroe Islands",
    code: "FO",
    unicode: "U+1F1EB U+1F1F4",
    emoji: "🇫🇴",
  },
  {
    name: "Micronesia, Federated States of",
    code: "FM",
    unicode: "U+1F1EB U+1F1F2",
    emoji: "🇫🇲",
  },
  { name: "Gabon", code: "GA", unicode: "U+1F1EC U+1F1E6", emoji: "🇬🇦" },
  {
    name: "United Kingdom",
    code: "GB",
    unicode: "U+1F1EC U+1F1E7",
    emoji: "🇬🇧",
  },
  { name: "Georgia", code: "GE", unicode: "U+1F1EC U+1F1EA", emoji: "🇬🇪" },
  { name: "Guernsey", code: "GG", unicode: "U+1F1EC U+1F1EC", emoji: "🇬🇬" },
  { name: "Ghana", code: "GH", unicode: "U+1F1EC U+1F1ED", emoji: "🇬🇭" },
  { name: "Gibraltar", code: "GI", unicode: "U+1F1EC U+1F1EE", emoji: "🇬🇮" },
  { name: "Guinea", code: "GN", unicode: "U+1F1EC U+1F1F3", emoji: "🇬🇳" },
  { name: "Guadeloupe", code: "GP", unicode: "U+1F1EC U+1F1F5", emoji: "🇬🇵" },
  { name: "Gambia", code: "GM", unicode: "U+1F1EC U+1F1F2", emoji: "🇬🇲" },
  {
    name: "Guinea-Bissau",
    code: "GW",
    unicode: "U+1F1EC U+1F1FC",
    emoji: "🇬🇼",
  },
  {
    name: "Equatorial Guinea",
    code: "GQ",
    unicode: "U+1F1EC U+1F1F6",
    emoji: "🇬🇶",
  },
  { name: "Greece", code: "GR", unicode: "U+1F1EC U+1F1F7", emoji: "🇬🇷" },
  { name: "Grenada", code: "GD", unicode: "U+1F1EC U+1F1E9", emoji: "🇬🇩" },
  { name: "Greenland", code: "GL", unicode: "U+1F1EC U+1F1F1", emoji: "🇬🇱" },
  { name: "Guatemala", code: "GT", unicode: "U+1F1EC U+1F1F9", emoji: "🇬🇹" },
  {
    name: "French Guiana",
    code: "GF",
    unicode: "U+1F1EC U+1F1EB",
    emoji: "🇬🇫",
  },
  { name: "Guam", code: "GU", unicode: "U+1F1EC U+1F1FA", emoji: "🇬🇺" },
  { name: "Guyana", code: "GY", unicode: "U+1F1EC U+1F1FE", emoji: "🇬🇾" },
  { name: "Hong Kong", code: "HK", unicode: "U+1F1ED U+1F1F0", emoji: "🇭🇰" },
  {
    name: "Heard Island and McDonald Islands",
    code: "HM",
    unicode: "U+1F1ED U+1F1F2",
    emoji: "🇭🇲",
  },
  { name: "Honduras", code: "HN", unicode: "U+1F1ED U+1F1F3", emoji: "🇭🇳" },
  { name: "Croatia", code: "HR", unicode: "U+1F1ED U+1F1F7", emoji: "🇭🇷" },
  { name: "Haiti", code: "HT", unicode: "U+1F1ED U+1F1F9", emoji: "🇭🇹" },
  { name: "Hungary", code: "HU", unicode: "U+1F1ED U+1F1FA", emoji: "🇭🇺" },
  { name: "Indonesia", code: "ID", unicode: "U+1F1EE U+1F1E9", emoji: "🇮🇩" },
  { name: "Isle of Man", code: "IM", unicode: "U+1F1EE U+1F1F2", emoji: "🇮🇲" },
  { name: "India", code: "IN", unicode: "U+1F1EE U+1F1F3", emoji: "🇮🇳" },
  {
    name: "British Indian Ocean Territory",
    code: "IO",
    unicode: "U+1F1EE U+1F1F4",
    emoji: "🇮🇴",
  },
  { name: "Ireland", code: "IE", unicode: "U+1F1EE U+1F1EA", emoji: "🇮🇪" },
  {
    name: "Iran, Islamic Republic of",
    code: "IR",
    unicode: "U+1F1EE U+1F1F7",
    emoji: "🇮🇷",
  },
  { name: "Iraq", code: "IQ", unicode: "U+1F1EE U+1F1F6", emoji: "🇮🇶" },
  { name: "Iceland", code: "IS", unicode: "U+1F1EE U+1F1F8", emoji: "🇮🇸" },
  { name: "Israel", code: "IL", unicode: "U+1F1EE U+1F1F1", emoji: "🇮🇱" },
  { name: "Italy", code: "IT", unicode: "U+1F1EE U+1F1F9", emoji: "🇮🇹" },
  { name: "Jamaica", code: "JM", unicode: "U+1F1EF U+1F1F2", emoji: "🇯🇲" },
  { name: "Jersey", code: "JE", unicode: "U+1F1EF U+1F1EA", emoji: "🇯🇪" },
  { name: "Jordan", code: "JO", unicode: "U+1F1EF U+1F1F4", emoji: "🇯🇴" },
  { name: "Japan", code: "JP", unicode: "U+1F1EF U+1F1F5", emoji: "🇯🇵" },
  { name: "Kazakhstan", code: "KZ", unicode: "U+1F1F0 U+1F1FF", emoji: "🇰🇿" },
  { name: "Kenya", code: "KE", unicode: "U+1F1F0 U+1F1EA", emoji: "🇰🇪" },
  { name: "Kyrgyzstan", code: "KG", unicode: "U+1F1F0 U+1F1EC", emoji: "🇰🇬" },
  { name: "Cambodia", code: "KH", unicode: "U+1F1F0 U+1F1ED", emoji: "🇰🇭" },
  { name: "Kiribati", code: "KI", unicode: "U+1F1F0 U+1F1EE", emoji: "🇰🇮" },
  {
    name: "Saint Kitts and Nevis",
    code: "KN",
    unicode: "U+1F1F0 U+1F1F3",
    emoji: "🇰🇳",
  },
  {
    name: "Korea, Republic of",
    code: "KR",
    unicode: "U+1F1F0 U+1F1F7",
    emoji: "🇰🇷",
  },
  { name: "Kuwait", code: "KW", unicode: "U+1F1F0 U+1F1FC", emoji: "🇰🇼" },
  {
    name: "Lao People's Democratic Republic",
    code: "LA",
    unicode: "U+1F1F1 U+1F1E6",
    emoji: "🇱🇦",
  },
  { name: "Lebanon", code: "LB", unicode: "U+1F1F1 U+1F1E7", emoji: "🇱🇧" },
  { name: "Liberia", code: "LR", unicode: "U+1F1F1 U+1F1F7", emoji: "🇱🇷" },
  { name: "Libya", code: "LY", unicode: "U+1F1F1 U+1F1FE", emoji: "🇱🇾" },
  { name: "Saint Lucia", code: "LC", unicode: "U+1F1F1 U+1F1E8", emoji: "🇱🇨" },
  {
    name: "Liechtenstein",
    code: "LI",
    unicode: "U+1F1F1 U+1F1EE",
    emoji: "🇱🇮",
  },
  { name: "Sri Lanka", code: "LK", unicode: "U+1F1F1 U+1F1F0", emoji: "🇱🇰" },
  { name: "Lesotho", code: "LS", unicode: "U+1F1F1 U+1F1F8", emoji: "🇱🇸" },
  { name: "Lithuania", code: "LT", unicode: "U+1F1F1 U+1F1F9", emoji: "🇱🇹" },
  { name: "Luxembourg", code: "LU", unicode: "U+1F1F1 U+1F1FA", emoji: "🇱🇺" },
  { name: "Latvia", code: "LV", unicode: "U+1F1F1 U+1F1FB", emoji: "🇱🇻" },
  { name: "Macao", code: "MO", unicode: "U+1F1F2 U+1F1F4", emoji: "🇲🇴" },
  {
    name: "Saint Martin (French part)",
    code: "MF",
    unicode: "U+1F1F2 U+1F1EB",
    emoji: "🇲🇫",
  },
  { name: "Morocco", code: "MA", unicode: "U+1F1F2 U+1F1E6", emoji: "🇲🇦" },
  { name: "Monaco", code: "MC", unicode: "U+1F1F2 U+1F1E8", emoji: "🇲🇨" },
  {
    name: "Moldova, Republic of",
    code: "MD",
    unicode: "U+1F1F2 U+1F1E9",
    emoji: "🇲🇩",
  },
  { name: "Madagascar", code: "MG", unicode: "U+1F1F2 U+1F1EC", emoji: "🇲🇬" },
  { name: "Maldives", code: "MV", unicode: "U+1F1F2 U+1F1FB", emoji: "🇲🇻" },
  { name: "Mexico", code: "MX", unicode: "U+1F1F2 U+1F1FD", emoji: "🇲🇽" },
  {
    name: "Marshall Islands",
    code: "MH",
    unicode: "U+1F1F2 U+1F1ED",
    emoji: "🇲🇭",
  },
  {
    name: "North Macedonia",
    code: "MK",
    unicode: "U+1F1F2 U+1F1F0",
    emoji: "🇲🇰",
  },
  { name: "Mali", code: "ML", unicode: "U+1F1F2 U+1F1F1", emoji: "🇲🇱" },
  { name: "Malta", code: "MT", unicode: "U+1F1F2 U+1F1F9", emoji: "🇲🇹" },
  { name: "Myanmar", code: "MM", unicode: "U+1F1F2 U+1F1F2", emoji: "🇲🇲" },
  { name: "Montenegro", code: "ME", unicode: "U+1F1F2 U+1F1EA", emoji: "🇲🇪" },
  { name: "Mongolia", code: "MN", unicode: "U+1F1F2 U+1F1F3", emoji: "🇲🇳" },
  {
    name: "Northern Mariana Islands",
    code: "MP",
    unicode: "U+1F1F2 U+1F1F5",
    emoji: "🇲🇵",
  },
  { name: "Mozambique", code: "MZ", unicode: "U+1F1F2 U+1F1FF", emoji: "🇲🇿" },
  { name: "Mauritania", code: "MR", unicode: "U+1F1F2 U+1F1F7", emoji: "🇲🇷" },
  { name: "Montserrat", code: "MS", unicode: "U+1F1F2 U+1F1F8", emoji: "🇲🇸" },
  { name: "Martinique", code: "MQ", unicode: "U+1F1F2 U+1F1F6", emoji: "🇲🇶" },
  { name: "Mauritius", code: "MU", unicode: "U+1F1F2 U+1F1FA", emoji: "🇲🇺" },
  { name: "Malawi", code: "MW", unicode: "U+1F1F2 U+1F1FC", emoji: "🇲🇼" },
  { name: "Malaysia", code: "MY", unicode: "U+1F1F2 U+1F1FE", emoji: "🇲🇾" },
  { name: "Mayotte", code: "YT", unicode: "U+1F1FE U+1F1F9", emoji: "🇾🇹" },
  { name: "Namibia", code: "NA", unicode: "U+1F1F3 U+1F1E6", emoji: "🇳🇦" },
  {
    name: "New Caledonia",
    code: "NC",
    unicode: "U+1F1F3 U+1F1E8",
    emoji: "🇳🇨",
  },
  { name: "Niger", code: "NE", unicode: "U+1F1F3 U+1F1EA", emoji: "🇳🇪" },
  {
    name: "Norfolk Island",
    code: "NF",
    unicode: "U+1F1F3 U+1F1EB",
    emoji: "🇳🇫",
  },
  { name: "Nigeria", code: "NG", unicode: "U+1F1F3 U+1F1EC", emoji: "🇳🇬" },
  { name: "Nicaragua", code: "NI", unicode: "U+1F1F3 U+1F1EE", emoji: "🇳🇮" },
  { name: "Niue", code: "NU", unicode: "U+1F1F3 U+1F1FA", emoji: "🇳🇺" },
  { name: "Netherlands", code: "NL", unicode: "U+1F1F3 U+1F1F1", emoji: "🇳🇱" },
  { name: "Norway", code: "NO", unicode: "U+1F1F3 U+1F1F4", emoji: "🇳🇴" },
  { name: "Nepal", code: "NP", unicode: "U+1F1F3 U+1F1F5", emoji: "🇳🇵" },
  { name: "Nauru", code: "NR", unicode: "U+1F1F3 U+1F1F7", emoji: "🇳🇷" },
  { name: "New Zealand", code: "NZ", unicode: "U+1F1F3 U+1F1FF", emoji: "🇳🇿" },
  { name: "Oman", code: "OM", unicode: "U+1F1F4 U+1F1F2", emoji: "🇴🇲" },
  { name: "Pakistan", code: "PK", unicode: "U+1F1F5 U+1F1F0", emoji: "🇵🇰" },
  { name: "Panama", code: "PA", unicode: "U+1F1F5 U+1F1E6", emoji: "🇵🇦" },
  { name: "Pitcairn", code: "PN", unicode: "U+1F1F5 U+1F1F3", emoji: "🇵🇳" },
  { name: "Peru", code: "PE", unicode: "U+1F1F5 U+1F1EA", emoji: "🇵🇪" },
  { name: "Philippines", code: "PH", unicode: "U+1F1F5 U+1F1ED", emoji: "🇵🇭" },
  { name: "Palau", code: "PW", unicode: "U+1F1F5 U+1F1FC", emoji: "🇵🇼" },
  {
    name: "Papua New Guinea",
    code: "PG",
    unicode: "U+1F1F5 U+1F1EC",
    emoji: "🇵🇬",
  },
  { name: "Poland", code: "PL", unicode: "U+1F1F5 U+1F1F1", emoji: "🇵🇱" },
  { name: "Puerto Rico", code: "PR", unicode: "U+1F1F5 U+1F1F7", emoji: "🇵🇷" },
  {
    name: "Korea, Democratic People's Republic of",
    code: "KP",
    unicode: "U+1F1F0 U+1F1F5",
    emoji: "🇰🇵",
  },
  { name: "Portugal", code: "PT", unicode: "U+1F1F5 U+1F1F9", emoji: "🇵🇹" },
  { name: "Paraguay", code: "PY", unicode: "U+1F1F5 U+1F1FE", emoji: "🇵🇾" },
  {
    name: "Palestine, State of",
    code: "PS",
    unicode: "U+1F1F5 U+1F1F8",
    emoji: "🇵🇸",
  },
  {
    name: "French Polynesia",
    code: "PF",
    unicode: "U+1F1F5 U+1F1EB",
    emoji: "🇵🇫",
  },
  { name: "Qatar", code: "QA", unicode: "U+1F1F6 U+1F1E6", emoji: "🇶🇦" },
  { name: "Réunion", code: "RE", unicode: "U+1F1F7 U+1F1EA", emoji: "🇷🇪" },
  { name: "Romania", code: "RO", unicode: "U+1F1F7 U+1F1F4", emoji: "🇷🇴" },
  {
    name: "Russian Federation",
    code: "RU",
    unicode: "U+1F1F7 U+1F1FA",
    emoji: "🇷🇺",
  },
  { name: "Rwanda", code: "RW", unicode: "U+1F1F7 U+1F1FC", emoji: "🇷🇼" },
  { name: "Saudi Arabia", code: "SA", unicode: "U+1F1F8 U+1F1E6", emoji: "🇸🇦" },
  { name: "Sudan", code: "SD", unicode: "U+1F1F8 U+1F1E9", emoji: "🇸🇩" },
  { name: "Senegal", code: "SN", unicode: "U+1F1F8 U+1F1F3", emoji: "🇸🇳" },
  { name: "Singapore", code: "SG", unicode: "U+1F1F8 U+1F1EC", emoji: "🇸🇬" },
  {
    name: "South Georgia and the South Sandwich Islands",
    code: "GS",
    unicode: "U+1F1EC U+1F1F8",
    emoji: "🇬🇸",
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    code: "SH",
    unicode: "U+1F1F8 U+1F1ED",
    emoji: "🇸🇭",
  },
  {
    name: "Svalbard and Jan Mayen",
    code: "SJ",
    unicode: "U+1F1F8 U+1F1EF",
    emoji: "🇸🇯",
  },
  {
    name: "Solomon Islands",
    code: "SB",
    unicode: "U+1F1F8 U+1F1E7",
    emoji: "🇸🇧",
  },
  { name: "Sierra Leone", code: "SL", unicode: "U+1F1F8 U+1F1F1", emoji: "🇸🇱" },
  { name: "El Salvador", code: "SV", unicode: "U+1F1F8 U+1F1FB", emoji: "🇸🇻" },
  { name: "San Marino", code: "SM", unicode: "U+1F1F8 U+1F1F2", emoji: "🇸🇲" },
  { name: "Somalia", code: "SO", unicode: "U+1F1F8 U+1F1F4", emoji: "🇸🇴" },
  {
    name: "Saint Pierre and Miquelon",
    code: "PM",
    unicode: "U+1F1F5 U+1F1F2",
    emoji: "🇵🇲",
  },
  { name: "Serbia", code: "RS", unicode: "U+1F1F7 U+1F1F8", emoji: "🇷🇸" },
  { name: "South Sudan", code: "SS", unicode: "U+1F1F8 U+1F1F8", emoji: "🇸🇸" },
  {
    name: "Sao Tome and Principe",
    code: "ST",
    unicode: "U+1F1F8 U+1F1F9",
    emoji: "🇸🇹",
  },
  { name: "Suriname", code: "SR", unicode: "U+1F1F8 U+1F1F7", emoji: "🇸🇷" },
  { name: "Slovakia", code: "SK", unicode: "U+1F1F8 U+1F1F0", emoji: "🇸🇰" },
  { name: "Slovenia", code: "SI", unicode: "U+1F1F8 U+1F1EE", emoji: "🇸🇮" },
  { name: "Sweden", code: "SE", unicode: "U+1F1F8 U+1F1EA", emoji: "🇸🇪" },
  { name: "Eswatini", code: "SZ", unicode: "U+1F1F8 U+1F1FF", emoji: "🇸🇿" },
  {
    name: "Sint Maarten (Dutch part)",
    code: "SX",
    unicode: "U+1F1F8 U+1F1FD",
    emoji: "🇸🇽",
  },
  { name: "Seychelles", code: "SC", unicode: "U+1F1F8 U+1F1E8", emoji: "🇸🇨" },
  {
    name: "Syrian Arab Republic",
    code: "SY",
    unicode: "U+1F1F8 U+1F1FE",
    emoji: "🇸🇾",
  },
  {
    name: "Turks and Caicos Islands",
    code: "TC",
    unicode: "U+1F1F9 U+1F1E8",
    emoji: "🇹🇨",
  },
  { name: "Chad", code: "TD", unicode: "U+1F1F9 U+1F1E9", emoji: "🇹🇩" },
  { name: "Togo", code: "TG", unicode: "U+1F1F9 U+1F1EC", emoji: "🇹🇬" },
  { name: "Thailand", code: "TH", unicode: "U+1F1F9 U+1F1ED", emoji: "🇹🇭" },
  { name: "Tajikistan", code: "TJ", unicode: "U+1F1F9 U+1F1EF", emoji: "🇹🇯" },
  { name: "Tokelau", code: "TK", unicode: "U+1F1F9 U+1F1F0", emoji: "🇹🇰" },
  { name: "Turkmenistan", code: "TM", unicode: "U+1F1F9 U+1F1F2", emoji: "🇹🇲" },
  { name: "Timor-Leste", code: "TL", unicode: "U+1F1F9 U+1F1F1", emoji: "🇹🇱" },
  { name: "Tonga", code: "TO", unicode: "U+1F1F9 U+1F1F4", emoji: "🇹🇴" },
  {
    name: "Trinidad and Tobago",
    code: "TT",
    unicode: "U+1F1F9 U+1F1F9",
    emoji: "🇹🇹",
  },
  { name: "Tunisia", code: "TN", unicode: "U+1F1F9 U+1F1F3", emoji: "🇹🇳" },
  { name: "Turkey", code: "TR", unicode: "U+1F1F9 U+1F1F7", emoji: "🇹🇷" },
  { name: "Tuvalu", code: "TV", unicode: "U+1F1F9 U+1F1FB", emoji: "🇹🇻" },
  {
    name: "Taiwan, Province of China",
    code: "TW",
    unicode: "U+1F1F9 U+1F1FC",
    emoji: "🇹🇼",
  },
  {
    name: "Tanzania, United Republic of",
    code: "TZ",
    unicode: "U+1F1F9 U+1F1FF",
    emoji: "🇹🇿",
  },
  { name: "Uganda", code: "UG", unicode: "U+1F1FA U+1F1EC", emoji: "🇺🇬" },
  { name: "Ukraine", code: "UA", unicode: "U+1F1FA U+1F1E6", emoji: "🇺🇦" },
  {
    name: "United States Minor Outlying Islands",
    code: "UM",
    unicode: "U+1F1FA U+1F1F2",
    emoji: "🇺🇲",
  },
  { name: "Uruguay", code: "UY", unicode: "U+1F1FA U+1F1FE", emoji: "🇺🇾" },
  {
    name: "United States",
    code: "US",
    unicode: "U+1F1FA U+1F1F8",
    emoji: "🇺🇸",
  },
  { name: "Uzbekistan", code: "UZ", unicode: "U+1F1FA U+1F1FF", emoji: "🇺🇿" },
  {
    name: "Holy See (Vatican City State)",
    code: "VA",
    unicode: "U+1F1FB U+1F1E6",
    emoji: "🇻🇦",
  },
  {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    unicode: "U+1F1FB U+1F1E8",
    emoji: "🇻🇨",
  },
  {
    name: "Venezuela, Bolivarian Republic of",
    code: "VE",
    unicode: "U+1F1FB U+1F1EA",
    emoji: "🇻🇪",
  },
  {
    name: "Virgin Islands, British",
    code: "VG",
    unicode: "U+1F1FB U+1F1EC",
    emoji: "🇻🇬",
  },
  {
    name: "Virgin Islands, U.S.",
    code: "VI",
    unicode: "U+1F1FB U+1F1EE",
    emoji: "🇻🇮",
  },
  { name: "Viet Nam", code: "VN", unicode: "U+1F1FB U+1F1F3", emoji: "🇻🇳" },
  { name: "Vanuatu", code: "VU", unicode: "U+1F1FB U+1F1FA", emoji: "🇻🇺" },
  {
    name: "Wallis and Futuna",
    code: "WF",
    unicode: "U+1F1FC U+1F1EB",
    emoji: "🇼🇫",
  },
  { name: "Samoa", code: "WS", unicode: "U+1F1FC U+1F1F8", emoji: "🇼🇸" },
  { name: "Yemen", code: "YE", unicode: "U+1F1FE U+1F1EA", emoji: "🇾🇪" },
  { name: "South Africa", code: "ZA", unicode: "U+1F1FF U+1F1E6", emoji: "🇿🇦" },
  { name: "Zambia", code: "ZM", unicode: "U+1F1FF U+1F1F2", emoji: "🇿🇲" },
  { name: "Zimbabwe", code: "ZW", unicode: "U+1F1FF U+1F1FC", emoji: "🇿🇼" },
];
